[theme]

# Primary accent for interactive elements
primaryColor = '#000000'

# Background color for the main content area
backgroundColor = '#05172e'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#2A629A'

# Color used for almost all text
textColor = '#F9F9E0'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"